import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import useSWR from "swr";
import styles from "../styles/Home.module.css";
import fetcher from "./fetcher";
import useDebounce from "./api/useDebouce";
import Realms from "./Realms";

export default function Home() {
  const [query, setQuery] = useState("Legion");

  function handleQueryChange(event, delay) {
    setQuery(event.target.value);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
      </main>
      <h2>Find your realm</h2>
      <input
        className={styles.search}
        id="query"
        autoComplete={"off"}
        onChange={handleQueryChange}
      ></input>

      <Realms query={query}></Realms>
      <div></div>
    </div>
  );
}
